## PRINT FUNCTION
from main_conventional import *
def print_variables():
    print('Iteration: ' + str(iter + 1))
    print("################TURBOPROP ################")
    print("The mass of the turboprop is "+ str(MTOW_tbp) + " [kg]")
    print("The calculated surface area is " + str(S_tbp) + " [m^2]")
    print("The maximum wing loading is " + str(W_S_landing_tbp[0][0]) + " [N/m^2]")
    print("The power weight ratio is " + str(W_P_tbp) + " [W/N]")
    print("The length of the fuselage is " + str(length_fuselage) + " [m]")
    print("The wing span is " + str(b_tbp) + " [m]")
    print("the taper ratio, root chrod and tip chord are " + str(t_c_ratio_tbp) + " [-]"+ str(root_chord_tbp) + " [m] "+ str(tip_chord_tbp) + " [m]")
    print("The cruise Mach number and the sweep are" + str(M_cruise_tbp) + "[m]" + str(sweep_tbp) + " [deg]")
    print("The engine diameter, engine length and prop diameter are " + str(diameter_engine_tbp) + " [m] " + str(length_engine_tbp) + " [m] " + str(diameter_propeller_tbp) + " [m]")
    print()
    print("################JET VALUES################")
    print("The mass of the jet is "+ str(MTOW_jet) + " [kg]")
    print("The calculated surface area is " + str(S_jet) + " [m^2]")
    print("The maximum wing loading is " + str(W_S_landing_jet) + " [N/m^2]")
    print("The thrust to weight ratio is " + str(T_W_jet_range[0]) + " [N/W]")
    print("The length of the fuselage is " + str(length_fuselage) + " [m]")
    print("The wing span is " + str(b_jet) + " [m]")
    print("the taper ratio, root chrod and tip chord are " + str(t_c_ratio_jet) + " [- ]"+ str(root_chord_jet) + " [m]"+ str(tip_chord_jet) + " [m]")
    print("The cruise Mach number and the sweep are" + str(M_cruise_jet) + "[m] " + str(sweep_jet) + " [deg]")
    print("The nacelle length, fan cowling length, hightlight diamter, fan exit diamter and gas generattor diamter are " + str(length_nacelle_jet)  + " [m] " + str(length_fan_cowling_jet) + " [m] "  + str(diameter_highlight_jet) + " [m] " + str(diameter_exit_fan_jet)  + " [m] " + str(diameter_gas_generator_jet)  + " [m]")
    